<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php $_product = $block->getProduct(); ?>
<?php if ($_product->isSaleable()): ?>

<div class="box-tocart actions">
  <a class="action primary tocart" href="<?php echo $block->getUrl('customer/account/login') ?>" title="<?php echo __('Login / Register') ?>"><?php echo __('Login / Register to Buy') ?></a>
</div>

<?php endif; ?>